#
# Makefile for the urbetter drivers
#

obj-$(CONFIG_OEM_GPIO_CFG)            += oem_gpio_cfg.o
obj-$(CONFIG_S706_GPIO_CFG)           += s706_gpio_cfg.o
obj-$(CONFIG_S502_GPIO_CFG)           += s502_gpio_cfg.o
obj-$(CONFIG_S106_GPIO_CFG)           += s106_gpio_cfg.o
obj-$(CONFIG_D105_GPIO_CFG)           += D105_gpio_cfg.o
obj-$(CONFIG_D720_GPIO_CFG)           += d720_gpio_cfg.o
