obj-$(CONFIG_URBETTER_POWER_GPIO) += power_gpio.o  power_gpio_common.o
obj-$(CONFIG_POWER_GPIO_D720_V1) +=power_gpio_d720_v1.o
obj-$(CONFIG_POWER_GPIO_D720_V4) +=power_gpio_d720_v4.o
obj-$(CONFIG_POWER_GPIO_S106) +=power_gpio_s106.o
obj-$(CONFIG_POWER_GPIO_D1011) +=power_gpio_d1011.o
obj-$(CONFIG_POWER_GPIO_D521) +=power_gpio_d521.o