#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_4212_105N)	+= goodix_touch_105n.o
obj-$(CONFIG_TOUCHSCREEN_NOVATEK_4X12_105N)	+= Novatek_TouchDriver.o
obj-$(CONFIG_TOUCHSCREEN_FT5X0X_105)	+= ft5x0x_ts_105.o
obj-$(CONFIG_TOUCHSCREEN_FT5X0X_5406)	+= ft5x0x_ts_5406.o
obj-$(CONFIG_TOUCHSCREEN_UC)	+= uc_logic.o
obj-$(CONFIG_TOUCHSCREEN_FT5X0X_5506)	+= ft5x0x_ts_5506.o
obj-$(CONFIG_TOUCHSCREEN_GT813_827_828)	+= gt813_827_828.o
obj-$(CONFIG_TOUCHSCREEN_GSLX680)	        += gslx680.o
obj-$(CONFIG_TOUCHSCREEN_VTL_CT36X)	+= vtl_ts/
obj-$(CONFIG_TOUCHSCREEN_GT912)	+=   GT/ 
obj-$(CONFIG_TOUCHSCREEN_GT911)	+=  gt9xx.o
